version: "3.9"

services:
  web:
    container_name: web
    build:
      dockerfile: Dockerfile
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    env_file:
      - .env
    environment:
      NODE_ENV: ${REACT_APP_ENV}
    ports:
      - "3000:3000"
