export const COUNTRIES = [
  { id: 34, option: "Россия" },
  { id: 33, option: "СССР" },
  { id: 1, option: "США" },
  { id: 3, option: "Франция" },
  { id: 10, option: "Италия" },
  { id: 8, option: "Испания" },
  { id: 5, option: "Великобритания" },
  { id: 9, option: "Германия" },
  { id: 49, option: "Корея Южная" },
  { id: 16, option: "Япония" },
  { id: 13, option: "Австралия" },
  { id: 128, option: "Беларусь" },
  { id: 12, option: "Германия (ФРГ)" },
  { id: 11, option: "Гонконг" },
  { id: 17, option: "Дания" },
  { id: 7, option: "Индия" },
  { id: 14, option: "Канада" },
  { id: 21, option: "Китай" },
  { id: 32, option: "Мальта" },
  { id: 55, option: "Марокко" },
  { id: 23, option: "Нидерланды" },
  { id: 29, option: "Новая Зеландия" },
  { id: 22, option: "Норвегия" },
  { id: 4, option: "Польша" },
  { id: 25, option: "Финляндия" },
  { id: 6, option: "Швеция" },
];

export default COUNTRIES;
